// modules/tracker/manifest.ts
//
// Auto-generated by framework scaffold. Edit via framework.scaffold
// operations from a Claude session, not by hand.

import type { CollectionMetadata } from '@baddabing/framework/data'

export interface SidebarItem {
  id: string
  label: string
  icon: string
  path: string
  title: string
}

export interface TrackerManifest {
  id: string
  name: string
  icon: string
  description: string
  basePath: string
  sidebar: SidebarItem[]
  collections?: CollectionMetadata[]
  schemaVersion?: number
  dependencies?: { modules?: string[] }
}

export const trackerModule: TrackerManifest = {
  id: 'tracker',
  name: 'Tracker',
  icon: '/icons/tracker.svg',
  description: 'Role evaluations and application materials',
  basePath: '/tracker',
  sidebar: [
    { id: 'home', label: 'TRA', icon: '/icons/tracker.svg', path: '/tracker', title: 'Tracker' },
  ],
  collections: [

  ],
  schemaVersion: 1,
  dependencies: { modules: [] },
}
