// modules/candidate/manifest.ts
//
// Auto-generated by framework scaffold. Edit via framework.scaffold
// operations from a Claude session, not by hand.

import type { CollectionMetadata } from '@baddabing/framework/data'

export interface SidebarItem {
  id: string
  label: string
  icon: string
  path: string
  title: string
}

export interface CandidateManifest {
  id: string
  name: string
  icon: string
  description: string
  basePath: string
  sidebar: SidebarItem[]
  collections?: CollectionMetadata[]
  schemaVersion?: number
  dependencies?: { modules?: string[] }
}

export const candidateModule: CandidateManifest = {
  id: 'candidate',
  name: 'Candidate',
  icon: '/icons/candidate.svg',
  description: 'Candidate profile, intel, and pipeline state',
  basePath: '/candidate',
  sidebar: [
    { id: 'home', label: 'CAN', icon: '/icons/candidate.svg', path: '/candidate', title: 'Candidate' },
  ],
  collections: [

  ],
  schemaVersion: 1,
  dependencies: { modules: [] },
}
