// app/candidate/api/upload/route.ts
//
// Auto-generated by @baddabing/framework scaffold.generateWrapperRoutes.
// Do not hand-edit — changes get overwritten by the next `pnpm
// generate-routes` run. Edit the source handlers in
// `@the-hunt/candidate`'s routes.ts instead.

export const runtime = 'nodejs'

export async function POST(req: Request): Promise<Response> {
  const mod = await import('@the-hunt/candidate')
  const handler = mod.routes["POST /upload"]
  if (!handler) {
    return new Response(
      JSON.stringify({
        error: {
          type: 'InternalError',
          message: "module 'candidate' does not export routes[POST /upload]",
        },
      }),
      { status: 500, headers: { 'Content-Type': 'application/json' } },
    )
  }
  return handler(req)
}
